version: "3.9"

services: 
    php:
        container_name: php-fpm
        build:
            context: ./docker/php
        volumes: 
            - "./:/var/www"            
        ports:
            - "9000:9000"
        restart: always
        environment:
            XDEBUG_CONFIG: client_host=${MYIP}
            DEBUG: 1        
    nginx:
        image: nginx
        container_name: ngnix
        restart: always
        volumes: 
            - "./:/var/www"   
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on: 
            - php
        ports: 
            - "8080:80"
        links: 
            - php